package akcome.oracle.apps.ap.invoice.request.negotiation.server;

import oracle.apps.ap.invoice.request.negotiation.server.NotifPGLineDetailsVOImpl;
import oracle.apps.ap.invoice.request.negotiation.server.NotificationPageAMImpl;

import oracle.jbo.server.ApplicationModuleImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NotificationPageAMExImpl extends NotificationPageAMImpl {
    /**This is the default constructor (do not remove)
     */
    public NotificationPageAMExImpl() {
    }

    /**Container's getter for NotifPGPaymentSchedulesVO1
     */
    public NotifPGPaymentSchedulesVOImpl getNotifPGPaymentSchedulesVO1() {
        return (NotifPGPaymentSchedulesVOImpl)findViewObject("NotifPGPaymentSchedulesVO1");
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("akcome.oracle.apps.ap.invoice.request.negotiation.server", /* package name */
      "NotificationPageAMExLocal" /* Configuration Name */);
    }
    
    public void initNotifPGPaymentSchedulesVO(String paramString)
    {
      getNotifPGPaymentSchedulesVO().executeQuery(paramString);
    }
    
    public NotifPGPaymentSchedulesVOImpl getNotifPGPaymentSchedulesVO()
    {
      return (NotifPGPaymentSchedulesVOImpl)findViewObject("NotifPGPaymentSchedulesVO");
    }

    /**Container's getter for NotificationPageAM
     */
    public ApplicationModuleImpl getNotificationPageAM() {
        return (ApplicationModuleImpl)findApplicationModule("NotificationPageAM");
    }
}

