package akcome.oracle.apps.ap.invoice.request.negotiation.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.apps.fnd.framework.OAException;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NotifPGPaymentSchedulesVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public NotifPGPaymentSchedulesVOImpl() {
    }

    /**This is the default constructor (do not remove)
     */
     public void executeQuery(String paramString)
     {
       setWhereClause(null);
        try{
        if (paramString != null)
        {
            setWhereClauseParam(0,paramString);
            
            executeQuery();
        }
        }catch (Exception localException1){
            throw OAException.wrapperException(localException1);
        }
    }
}
