package akcome.oracle.apps.ap.invoice.request.negotiation.server;

import oracle.apps.ap.invoice.request.negotiation.server.NotifPGLineDetailsVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NotifPGLineDetailsVOExImpl extends NotifPGLineDetailsVOImpl {
    /**This is the default constructor (do not remove)
     */
    public NotifPGLineDetailsVOExImpl() {
    }
}
