package akcome.oracle.apps.icx.por.wf.server;

import oracle.apps.icx.por.wf.server.ReqLinesNotificationsVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReqLinesNotificationsVOExImpl extends ReqLinesNotificationsVOImpl {
    /**This is the default constructor (do not remove)
     */
    public ReqLinesNotificationsVOExImpl() {
    }
}
