package akcome.oracle.apps.ap.oie.workflow.apexp.server;

import oracle.apps.ap.oie.workflow.apexp.server.NotifExpLinesVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NotifCashLinesVOExImpl extends NotifExpLinesVOImpl {
    /**This is the default constructor (do not remove)
     */
    public NotifCashLinesVOExImpl() {
    }
}
