package akcome.oracle.apps.po.notifications.server;

import oracle.apps.po.notifications.server.PoNotifLinesSummaryVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PoNotifLinesSummaryVOExImpl extends PoNotifLinesSummaryVOImpl {
    /**This is the default constructor (do not remove)
     */
    public PoNotifLinesSummaryVOExImpl() {
    }
}
